import org.gradle.api.initialization.resolve.RepositoriesMode

gradle.settingsEvaluated { settings ->
    settings.pluginManagement {
        repositories {
            gradlePluginPortal()
            mavenCentral()
            mavenLocal()
        }
    }

    settings.dependencyResolutionManagement {
        repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
        repositories {
            mavenCentral()
            mavenLocal()
        }
    }
}